name: CI unsafe

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

# Grant no permissions by default. Jobs opt into what they need.
# See https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
permissions: {}

# Cancel outdated runs for the same PR or branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  sanitizers:
    name: Run sanitizers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2.9.2
      - run: |
            # to get the symbolizer for debug symbol resolution
            sudo apt install llvm
            # to fix buggy leak analyzer:
            # https://github.com/japaric/rust-san#unrealiable-leaksanitizer
            # ensure there's a profile.dev section
            if ! grep -qE '^[ \t]*[profile.dev]' Cargo.toml; then
                echo >> Cargo.toml
                echo '[profile.dev]' >> Cargo.toml
            fi
            # remove pre-existing opt-levels in profile.dev
            sed -i '/^\s*\[profile.dev\]/,/^\s*\[/ {/^\s*opt-level/d}' Cargo.toml
            # now set opt-level to 1
            sed -i '/^\s*\[profile.dev\]/a opt-level = 1' Cargo.toml
            cat Cargo.toml
      - run: |
          # only --lib --tests b/c of https://github.com/rust-lang/rust/issues/53945
          cargo test --lib --tests --all-features --target x86_64-unknown-linux-gnu
        env:
          ASAN_OPTIONS: "detect_odr_violation=0:detect_leaks=0"
          RUSTFLAGS: "-Z sanitizer=address"
      - run: cargo test --all-features --target x86_64-unknown-linux-gnu
        if: always()
        env:
          LSAN_OPTIONS: "suppressions=lsan-suppressions.txt"
          RUSTFLAGS: "-Z sanitizer=leak"
  miri:
    name: Run Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - run: |
          echo "NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)" >> "$GITHUB_ENV"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY }}
          components: miri
      - uses: Swatinem/rust-cache@v2.9.2
      - run: cargo miri test
        env:
          MIRIFLAGS: ""
  loom:
    name: Run Loom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.9.2
      - run: cargo test --release --test loom
        env:
          LOOM_MAX_PREEMPTIONS: 2
          RUSTFLAGS: "--cfg loom"
